### ISSUE TITLE
Problem cancelling the download promise

### ISSUE THREAD

**Issue by marcelomiura** [sgrebnov/cordova-plugin-background-download#4]
My app crashes when I try to cancel my download promise. It seems that when the download process is completed, the BroadcastReceiver tries to manage the download and throw some exception.

Here's what I got: 
`Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.teste.download (has extras) } in org.apache.cordova.backgroundDownload.BackgroundDownload
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:737)
at android.os.Handler.handleCallback(Handler.java:605)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4514)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0`

**Comment by NickToropov** [comment]
Hi guys, we've made a number of improvements recently that fix this issue too.

I'll close it for now but feel free to reopen it if you have any questions.
