### ISSUE TITLE
Error Installing cordova-plugin-background-download

### ISSUE THREAD

**Issue by UlyssesAlves** [sgrebnov/cordova-plugin-background-download#42]
I`m gettting the error below when I try to install this plugin on Mac:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'https://github.com/sgrebnov/cordova-plugin-background-download.git',
1 verbose cli   '--production',
1 verbose cli   '--save' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose npm-session 540257cedfdee7e8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/sgrebnov/cordova-plugin-background-download.git Non-registry package missing package.json: git+https://github.com/sgrebnov/cordova-plugin-background-download.git.
8 verbose stack Error: Non-registry package missing package.json: git+https://github.com/sgrebnov/cordova-plugin-background-download.git.
8 verbose stack     at BB.join (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/finalize-manifest.js:160:23)
8 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
8 verbose stack     at Holder$5._callFunction (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
8 verbose stack     at Holder$5.checkFulfillment (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
8 verbose stack     at Promise.eval (eval at thenCallback (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
8 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
8 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
8 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
8 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
8 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
8 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
8 verbose stack     at runCallback (timers.js:789:20)
8 verbose stack     at tryOnImmediate (timers.js:751:5)
8 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
9 verbose cwd /Users/ulyssesalves/Desktop/Dev/Projetos/playervozdosetimoanjo/player-voz-do-ceu-cordova
10 verbose Darwin 17.0.0
11 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/sgrebnov/cordova-plugin-background-download.git" "--production" "--save"
12 verbose node v8.9.0
13 verbose npm  v5.5.1
14 error code ENOPACKAGEJSON
15 error package.json Non-registry package missing package.json: git+https://github.com/sgrebnov/cordova-plugin-background-download.git.
16 error package.json npm can't find a package.json file in your current directory.
17 verbose exit [ 1, true ]

```

**Comment by NickToropov** [comment]
Hi @UlyssesAlves, thanks for posting the issue. The problem should be fixed with commit#2dae083ccd2214010b757ce59f83ad8a7f59bf1c.

I'll close it for now, but please feel free to reopen it if you have any questions.
